name: "FirstComment"

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, '[CHESS]')
    steps:
      - uses: actions/checkout@v2
      - name: Randomize Player Color
        id: color
        run: |
          res=$(($RANDOM%2))
          if [[ ${res} -eq 0 ]]; then
              echo "::set-output name=white::${{ github.event.repository.owner.login }}"
              echo "::set-output name=black::${{ github.event.issue.user.login }}"
          elif [[ ${res} -eq 1 ]]; then
              echo "::set-output name=white::${{ github.event.issue.user.login }}"
              echo "::set-output name=black::${{ github.event.repository.owner.login }}"
          fi
      - name: Add Comment w/Player Pieces
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ### New Game!
            @${{ steps.color.outputs.white }} (white) vs @${{ steps.color.outputs.black }} (black)
      - name: Create initial board
        id: board
        run: |
          BOARD="$(python3 ./scripts/fen2md.py 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')"
          BOARD="$(python3 ./scripts/replace_images.py $BOARD)"
          BOARD="${BOARD//'%'/'%25'}"
          BOARD="${BOARD//$'\n'/'%0A'}"
          BOARD="${BOARD//$'\r'/'%0D'}"
          echo "::set-output name=board::$BOARD"
      - name: Add Comment w/Board
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ### Board: White to Play

            ${{ steps.board.outputs.board }}
