name: "FirstComment"

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, '[CHESS]')
    steps:
      - name: Add Comment w/Player Pieces
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ### New Game!
            @user1 (white) vs @user2 (black)
      - name: Add Comment w/Board
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ### Board: White to Play
            <Initial Board Representation>
