name: "FirstComment"

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, '[CHESS]')
    steps:
      - name: Add Comment w/Board
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Made with [BobbyFissue](https://github.com/FdelMazo/BobbyFissue)
