name: "UpdateBoard"

on:
  issue_comment:
    types: [created]

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, '[CHESS]')
    steps:
      - uses: actions/checkout@v2
      - name: Find Board Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: "github-actions[bot]"
          body-includes: "### Board"
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: chess
      - name: Parse Move and Board
        id: parser
        run: |
          CURRFEN="$(echo "${{ steps.fc.outputs.comment-body }}" | grep '>' | tr -d '>`')"
          echo "::set-output name=current_fen::$CURRFEN"
      - name: Play Move
        id: fen
        run: |
          FEN="$(python3 ./scripts/chessmove.py ${{steps.parser.outputs.current_fen}} ${{steps.parser.outputs.next_move}}"
          echo "::set-output name=fen::$FEN"
      - name: Show Move
        id: board
        run: |
          BOARD="$(python3 ./scripts/fen2md.py "${{steps.fen.outputs.fen}}" | python3 ./scripts/replace_images.py)"
          BOARD="${BOARD//'%'/'%25'}"
          BOARD="${BOARD//$'\n'/'%0A'}"
          BOARD="${BOARD//$'\r'/'%0D'}"
          echo "::set-output name=board::$BOARD"
      - name: Edit Board Comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            ### Board: ${{ steps.fc.outputs.comment-id }} to Play
            > `${{steps.fen.outputs.fen}}`
            ${{ steps.board.outputs.board }}
